apiVersion: v1
kind: Service
metadata:
  name: flask-lb
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 3000
      protocol: "TCP"
    - name: http
      port: 80
      targetPort: 3000
      protocol: "TCP"
  selector:
    app: flask
