apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: "TCP"
  selector:
    app: {{ include "flask-app-chart.name" . }}
